My_Blog/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name = "index"),
    path('about/', views.AboutPage.as_view(), name = "about"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls', namespace="posts"))
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', 
        auth_views.LoginView.as_view(template_name = 'accounts/login.html'),
        name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

posts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name="post_list"),
    path('<int:pk>/', views.post_detail.as_view(), name="detail"),
    path('<int:pk>/comment/', views.add_comment_to_post, name="add_comment"),
    path('new_post/', views.create_post, name="new_post"),
    path('<int:pk>/detail/modify', views.post_modify, name="modify"),
    path('<int:pk>/post/delete/', views.post_delete, name="post_delete"),
    path('<int:pk>/comment/delete/', views.comment_delete, name="comment_delete"),
    path('<int:pk>/post/vote/', views.vote_post, name="vote_post"),
    path('<int:pk>/post/vote_comment/', views.vote_comment, name="vote_comment"),
]

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return self.username

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 200)
    content = models.TextField()
    author = models.ForeignKey(User,null=True, on_delete=models.CASCADE, related_name='author_post')
    create_date = models.DateTimeField(auto_now=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_post')

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_comment')
    create_date = models.DateTimeField(auto_now=True)
    voter = models.ManyToManyField(User, related_name='voter_comment')

    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        

posts/forms.py
from django import forms
from .models import Post, Comment

class Create_Post_Form(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content']
    
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'row':10}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

        

My_Blog/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

class AboutPage(TemplateView):
    template_name = 'about.html'

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from . import forms
from django.views.generic import CreateView

class SignUp(CreateView):  
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from . import models
from . import forms
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q, Count

# Create your views here.
def post_list(request):
    # Input Parameter
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw',)

    #Sort
    search_option = request.GET.get('search_option', 'recent')  #default

    if search_option == 'recommend':
        post_list = models.Post.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif search_option == 'popular':
        post_list = models.Post.objects.annotate(num_comment=Count('comment')).order_by('-num_comment','-create_date')
    else:
        post_list = models.Post.objects.order_by('-create_date')

    # Look up
   
    if kw:
        post_list = post_list.filter(
            Q(title__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) 
        ).distinct()

    paginator=Paginator(post_list, 15)
    page_obj = paginator.get_page(page)

    context = {'post_list':page_obj, 'page':page, 'kw':kw}

    return render(request, 'posts/post_list.html', context)

class post_detail(generic.DetailView):
    model = models.Post
    context_object_name = 'post_detail'
    template_name = 'posts/post_detail.html'

@login_required(login_url='accounts:login')
def create_post(request):
    if request.method == 'POST':
        form = forms.Create_Post_Form(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.create_date = timezone.now()
            post.author = request.user
            post.save()
            return redirect('posts:post_list')
    else:
        form = forms.Create_Post_Form()
    context = {'form':form}
    return render(request, 'posts/create_post.html', context)
    
@login_required(login_url='accounts:login')
def add_comment_to_post(request, pk):
    post = get_object_or_404(models.Post, pk=pk)

    if request.method == "POST":
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.create_date = timezone.now()
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('posts:detail', pk = pk), comment.id))
    else:
        form = forms.CommentForm()

    context = {'post':post, 'form':form}
    return render(request, 'posts/post_list.html', context)

@login_required(login_url='accounts:login')
def post_modify(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    
    if request.method == "POST":
        form = forms.Create_Post_Form(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.modify_date = timezone.now()
            post.save()
            return redirect('posts:detail', pk = pk)
    else:
        form = forms.Create_Post_Form(instance=post)
    context = {'form':form}
    return render(request, 'posts/create_post.html', context)


@login_required(login_url='accounts:login')
def post_delete(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    
    post.delete()
    return redirect('posts:post_list')

@login_required(login_url='accounts:login')
def comment_delete(request, pk):
    comment = get_object_or_404(models.Comment, pk=pk)
    
    comment.delete()
    return redirect('posts:detail', pk=comment.post.pk)

@login_required(login_url='accounts:login')
def vote_post(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    if post.voter.filter(pk=request.user.id).exists():
        post.voter.remove(request.user)
    else:
        post.voter.add(request.user)
    return redirect('posts:detail', pk=post.pk)

@login_required(login_url='accounts:login')
def vote_comment(request, pk):
    comment = get_object_or_404(models.Comment, pk=pk)
    if comment.voter.filter(pk=request.user.id).exists():
        comment.voter.remove(request.user)
    else:
        comment.voter.add(request.user)
    return redirect('{}#comment_{}'.format(
                resolve_url('posts:detail', pk = comment.post.pk), comment.id))

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load socialaccount %}
{% providers_media_js %}

{% block content %}
<div class="container" id="login_page">
    <h1>Log In</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Log In">
    </form>
    <p></p>
    <a class="btn btn-success" role="button" href="{% provider_login_url "google" %}">
        <img src="{% static 'image/google_icon.png' %}" width="40px" height="40px" style="margin-right:10px;">Google Log In</a>

</div>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block content %}

<!-- Post Information -->


<div class="card">
    <div class="card-header" style="display:flex;">
        <strong style="font-size: 1.5em;">{{ post_detail.title }}</strong>

        <!-- Recommend Button -->
        <div class="bg-light text-center border font-weight-bolder" ,
            style="width:3%; height:31px; margin-left:1%; margin-top:4px; margin-right:1%">{{ post_detail.voter.count }}
        </div>
        {% if user.is_authenticated %}
        <a href="#" data-uri="{% url 'posts:vote_post' pk=post_detail.pk %}"
            class="recommend btn btn-sm btn-secondary btn-block my-1" style="width:4%"><i
                class="fas fa-thumbs-up"></i></a>
        {% else %}
        <a href="{% url 'accounts:login' %}" class="recommend btn btn-sm btn-secondary btn-block my-1"
            style="width:4%"><i class="fas fa-thumbs-up"></i></a>
        {% endif %}

    </div>

    <div class="card-body">
        <!-- Post Information -->
        <div class="user_info row justify-content-between my-8" style="font-size: 0.8em;">
            <div class="col-1">
                {{ post_detail.author.username }}
            </div>
            <div class="col-2" style="margin-left:75%;">
                {% if not post_detail.modify_date %}
                {{ post_detail.create_date }}
                {% else %}
                {{ post_detail.modify_date }}
                {% endif %}
            </div>
            </br></br></br>
        </div>

        <p class="card-text">{{ post_detail.content }}</p>

    </div>
    </br></br>
    <!-- Modify, Delete Button -->
    <div class="modify_delete" style="margin-left:85%">
        {% if request.user == post_detail.author %}
        <div class="my-3">
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'posts:modify' pk=post_detail.pk %}">Modify</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary"
                data-uri="{% url 'posts:post_delete' pk=post_detail.pk %}">Delete</a>
        </div>
        {% endif %}
    </div>

</div>


<!-- Comment Information -->
<br />
<div class="card">
    <div class="card-header" style="font-size:0.75em">
        <strong>{{ post_detail.comment_set.count }} comments.</strong>
    </div>
    <div class="card-body">
        <hr />
        {% for comment in post_detail.comment_set.all %}

        <div class="comment_body" style="display:flex;">
            <div class="comment_body_top" style="width:85%;padding-left:20px; font-size:0.8em">
                <div style="font-size: 0.9em;"><strong>{{ comment.author.username }}</strong><cite
                        title="Source Title" style="margin-left:1%; font-size: 0.85em;">{{ comment.create_date }}</cite>
                </div>
                {{ comment.content }}
            </div>

            <div class="delete_button">
                {% if request.user == comment.author %}
                <div class="my-3" style="padding-left:55px; margin-bottom: 10px;">
                    <a href="#" class="delete btn btn-sm btn-outline-danger"
                        data-uri="{% url 'posts:comment_delete' pk=comment.pk %}" style="font-size:0.5em;">Delete</a>
                </div>
                {% endif %}
            </div>
        </div>

        <div class="recommend_comment" style="display:flex; margin-left:20px">
            <a name="comment_{{ comment.id }}"></a>
            <div class="bg-light text-center" style="width:3px;height:10px;font-size: 0.8em; margin-top:7px">{{ comment.voter.count }}</div>
            {% if user.is_authenticated %}
            <a href="#" data-uri="{% url 'posts:vote_comment' pk=comment.pk %}" class="recommend btn btn-sm" ><svg
                    xmlns="http://www.w3.org/2000/svg" width="14" height="10" fill="currentColor"
                    class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                    <path
                        d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z" />
                </svg>
            </a>
            {% else %}
            <a href="{% url 'accounts:login' %}" class="recommend btn btn-sm"><svg
                    xmlns="http://www.w3.org/2000/svg" width="14" height="10" fill="currentColor"
                    class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                    <path
                        d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z" />
                </svg></a>
            {% endif %}
        </div>
        <hr />
        {% endfor %}
    </div>

    <div class="Add_Comment">
        <form action="{% url 'posts:add_comment' pk=post_detail.pk %}" method="POST">
            {% csrf_token %}
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
    
            {% if user.is_authenticated %}
            <textarea name="content" id="content" rows="5" cols="110" style="margin-left:10%;resize:none;" required></textarea>
            <input type="submit" class="btn btn-primary" value="Add Comment" style="margin-bottom:120px">
            {% endif %}
        </form>
    </div>
</div>

<br /><br /><br />
{% endblock %}

<!-- Script for alert when deleting -->
{% block script %}
<script type='text/javascript'>
    $(document).ready(function () {
        $(".delete").on('click', function () {
            if (confirm("Are you sure to delete?")) {
                location.href = $(this).data('uri');
            }
        });

        $(".recommend").on('click', function () {
            location.href = $(this).data('uri');
        });
    });
</script>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block content %}

<div class="container my-3">
    <div class="row justify-content-between my-8">   

        <div class="col-2">
            <select class="form-control search_option">
                <option value="recent" {% if search_option == 'recent' %}selected{% endif %}>Most Recent</option>
                <option value="recommend" {% if search_option == 'recommend' %}selected{% endif %}>Recommend</option>
                <option value="popular" {% if search_option == 'popular' %}selected{% endif %}>Popular</option>
            </select>
        </div>

        <div class="col-5 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search"
                    style="height:38px;">Search</button>
            </div>
        </div>

        <div class="col-2" style="padding-left:70px;">
            {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'posts:new_post' %}">New Post</a><p></p>
            {% else %}
                <a class="btn btn-primary" href="{% url 'accounts:login' %}">New Post</a><p></p>
            {% endif %}
        </div>
        
    </div>


<table class="table">
    <thead>
    <tr class="thead-dark">
        <th class="text-center">Recommends</th>
        <th style="width:50%">Title</th>
        <th>User Name</th>
        <th>Post Date</th>
    </tr>
    </thead>

    <tbody>
    {% if post_list %}
        {% for post in post_list %}
    <tr>
        <td class="text-center">
            <span class="badge px-2 py-1">{{ post.voter.all.count }}</span>
        </td>

        <td>
            <a href="{% url 'posts:detail' pk=post.pk %}">{{ post.title }}</a>
            {% if post.comment_set.count > 0 %}
                <span class="badge badge-secondary text-wrap" style="margin-left:20px">{{ post.comment_set.count }}</span>
            {% endif %}
        </td>

        <td>{{ post.author.username }}</td>
        <td>{{ post.create_date }}</td>
    </tr>
        {% endfor %}
    {% endif %}
    </tbody>
</table>
            



</div>

<ul class="pagination justify-content-center">
    <!-- Previous Page -->
    {% if post_list.has_previous %}
    <li class="page-item">
        <a class="page-link" data-page="{{ post_list.previous_page_number }}" href="#">Prev</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Prev</a>
    </li>
    {% endif %}
    <!-- Page List -->
    {% for page_number in post_list.paginator.page_range %}
        {% if page_number >= post_list.number|add:-5 and page_number <= post_list.number|add:5 %}
            {% if page_number == post_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
    {% endfor %}
    <!-- Next Page -->
    {% if post_list.has_next %}
    <li class="page-item">
        <a class="page-link" data-page="{{ post_list.next_page_number }}" href="#">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
    </li>
    {% endif %}
</ul>
<!-- Done Paginating -->

<!-- Search Form -->
<form id="searchForm" method="get" action="{% url 'posts:post_list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="search_option" name="search_option" value="{{ search_option }}">
</form>

{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".search_option").on('change', function(){
        $("#search_option").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    })
});
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Yeongbin Kim Blog</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/master.css'%}">

    <!-- Bootstrap 4 CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <!-- Bootstrap 5 CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
    <!-- font-family: 'Indie Flower', cursive; -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
    <!-- font-family: 'Architects Daughter', cursive; -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <!-- font-family: 'Nunito', sans-serif; -->

    <!-- jQuery -->
    <script src="http://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
    
</head>

<body>
    <!-- Nav Bar -->
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light static-top">
            <a class="navbar-brand" href="{% url 'index' %}" style="font-size: 30px;"><span
                    class="badge badge-secondary">My_Blog</span></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'posts:post_list' %}">Post</a></li>
                    <!-- <li class="nav-item"><a class="nav-link" href="#">My Blog</a></li> -->

                    <li class="nav-item"><a class="nav-link" href="/#about">About</a></li>
                </ul>

                <ul class="navbar-nav ml-auto">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Link
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="https://github.com/sjyb9394">Github</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item"
                                href="https://www.linkedin.com/in/yeongbin-kim-07590b16b/">Linkedin</a>
                        </div>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>

            </div>
        </nav>
        <hr />

    </div>
    <div class="container" id="body_content">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

    {% block script %}
    {% endblock %}

</body>

</html>